name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'green'

# Define your inputs here.
inputs:
  token:
    description: 'Your GitHub token'
    required: true
  ref:
    description: 'The ref to check'
    required: true
  poll-frequency:
    description: 'How often to poll for check statuses in seconds'
    required: false
    default: '15'
  timeout:
    description: 'How long to wait for checks to complete in seconds'
    required: false
    default: '900' # 15 minutes

runs:
  using: node20
  main: dist/index.js
